export const SUBSCRIPTION_STATUSES = [
  'ACTIVE',
  'COMPLETED',
  'SUPERSEDED',
  'CANCELLED',
] as const;

export type SubscriptionStatus = (typeof SUBSCRIPTION_STATUSES)[number];

export const SUBSCRIPTION_AUDIT_OPERATIONS = {
  ACTIVATE_FROM_DEPOSIT: 'ACTIVATE_PACKAGE_FROM_DEPOSIT',
  AUTO_ACTIVATE_AFTER_ACCOUNTING: 'AUTO_ACTIVATE_PACKAGE_AFTER_ACCOUNTING',
  RECONCILE_ACTIVATION: 'RECONCILE_PACKAGE_ACTIVATION',
} as const;
